gdb-cross_linaro-7.8: remove elf_prstatus-size.patch
elf_prstatus-size.patch no longer applies as the patched file no longer
exists.
The patched code now resides in gdb-linaro-7.8-2014.09/bfd/elfxx-aarch64.c
with the patch already applied.

  ERROR: Command Error: exit status: 1  Output:
  Applying patch elf_prstatus-size.patch
  can't find file to patch at input line 5

Change-Id: I74a89778e4aaf6d08ead0a84ba3ea26792245f06
Signed-off-by: Max Krummenacher <max.oss.09@gmail.com>