qt4-x11-free 4.8.6 bbappend: update patch
OE-core added mips64 support which clashes with our armv8 support. This fixes:

ERROR: Command Error: exit status: 1  Output:
Applying patch aarch64.patch
patching file src/3rdparty/webkit/Source/JavaScriptCore/wtf/Platform.h
Hunk #1 succeeded at 371 (offset 4 lines).
Hunk #2 FAILED at 1001.
1 out of 2 hunks FAILED -- rejects in file src/3rdparty/webkit/Source/JavaScriptCore/wtf/Platform.h
Patch aarch64.patch does not apply (enforce with -f)
ERROR: Function failed: patch_do_patch
ERROR: Logfile of failure stored in: /build/scratch/angstrom-v2014.12/build/tmp-angstrom_next-eglibc/work/armv7at2hf-vfp-angstrom-linux-gnueabi/qt4-x11-free/4.8.6-r0/temp/log.do_patch.21352
ERROR: Task 1 (/build/scratch/angstrom-v2014.12/sources/openembedded-core/meta/recipes-qt/qt4/qt4-x11-free_4.8.6.bb, do_patch) failed with exit code '1'

Change-Id: I155749907835df33d432d87340e81efd0ef234d6
Signed-off-by: Koen Kooi <koen.kooi@linaro.org>